server:
  port: 8888

spring:
  application:
    name: cloudConfig
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: vault
            host: localhost
            port: 8200
            scheme: http
            backend: secret
            kv-version: 2
            default-key: application
            profile-separator: /
            token: myroot
          - type: git
            uri: https://github.com/ermiasashebr/cloud-config
            clone-on-start: true
            default-label: main
        


management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,beans,metrics,threaddump	  

logging:
  level:
    org.springframework.cloud.config.server.environment: DEBUG
    org.springframework.vault: DEBUG

          

